#!/bin/bash
#SBATCH --job-name=fine-tune-bert
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=180g
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --account=mihalcea
#SBATCH --mail-type=BEGIN,END
#SBATCH --time=48:00:00
#SBATCH --mail-user=jiajunb@umich.edu

./bin/train.sh
